[package]
name = "nfd2c"
version = "0.3.3"
edition = "2021"
description = "Converts NFD-formatted file names to NFC format"
license = "MIT"

[dependencies]
unicode-normalization = "0.1"
clap = { version = "4.5.19", features = ["derive"] }
walkdir = "2.5"
